wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.5
    cli_version: 0.15.12
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699403597.059924
    t:
      1:
      - 55
      - 105
      2:
      - 55
      - 105
      3:
      - 7
      - 23
      4: 3.8.5
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: loss
      6:
      - 3
      7:
      - 1
    - 1: acc
      6:
      - 3
      7:
      - 2
